name: Deploy to Glitch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Deploy to Glitch
      env:
        GLITCH_PROJECT_ID: ${{ secrets.GLITCH_PROJECT_ID }}
        GLITCH_REPO: ${{ secrets.GLITCH_REPO }}
        GLITCH_BRANCH: ${{ secrets.GLITCH_BRANCH }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git remote add glitch https://api.glitch.com/git/${{ secrets.GLITCH_PROJECT_ID }}
        git push glitch ${{ secrets.GLITCH_BRANCH }}:master --force
